# Generated by Django 4.2 on 2025-11-18 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('stock', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_ingreso', models.DateField()),
                ('categoria', models.CharField(choices=[('herramientas', 'Herramientas'), ('pintura', 'Pintura'), ('pisos', 'Pisos'), ('jardineria', 'Jardineria')], max_length=20)),
            ],
        ),
    ]
